FROM node:20-alpine AS builder
WORKDIR /app

# Install system dependencies for Prisma (OpenSSL + libc compatibility)
RUN apk add --no-cache openssl libc6-compat

# Environment & NPM tuning
ENV NPM_CONFIG_LOGLEVEL=warn \
    NPM_CONFIG_REGISTRY=https://registry.npmjs.org \
    NEXT_TELEMETRY_DISABLED=1

# Copy package manifests and prisma schema.  We include the lockfile and
# lockfile-check script to ensure dependency determinism.  Do not remove
# package-lock.json — instead validate it via lockfile-check.js and use
# npm ci for reproducible installs.
COPY package.json package-lock.json ./
COPY prisma ./prisma
COPY lockfile-check.js ./
# Copy scripts directory before npm install to ensure postinstall scripts can run
COPY scripts ./scripts

# Validate the lockfile matches package.json expectations.  This will
# exit with a non-zero code if there is a mismatch (e.g. after an
# accidental dependency upgrade) so builds fail early.
RUN node ./lockfile-check.js

# Install all dependencies using npm ci.  This command relies on the
# existing lockfile to perform a clean, reproducible install and
# includes devDependencies required for the build step.
RUN npm ci --no-audit --no-fund

# Generate the Prisma client before copying application source.  This
# ensures that @prisma/client types exist for TypeScript compilation.
RUN npx prisma generate

# Copy application source.  Note that node_modules and prisma have
# already been copied.
COPY . .

# Build the Next.js application.  This triggers TypeScript type
# checking and emits the `.next` output used in production.
RUN npm run build

# Prune devDependencies.  After the build completes, only production
# dependencies are required at runtime.  Using npm prune with
# production flag removes dev dependencies from node_modules.
RUN npm prune --production

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1

RUN apk add --no-cache openssl libc6-compat wget

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy build artifacts from builder
# 1. Public assets
COPY --from=builder /app/public              ./public

# 2. Next.js standalone output (includes server.js at root)
COPY --from=builder /app/.next/standalone    ./

# 3. Static assets generated by Next.js
COPY --from=builder /app/.next/static        ./.next/static

# 4. Prisma schema + migrations (needed for migrate deploy at startup)
COPY --from=builder /app/prisma              ./prisma

# 5. Full production node_modules from builder (pruned of devDeps).  The
#    standalone output only bundles modules Next.js pages import.  The
#    custom server.ts needs socket.io, web-push, argon2, tsx and all
#    their transitive dependencies.  Copying the entire node_modules
#    ensures every dependency is present.
COPY --from=builder /app/node_modules        ./node_modules

# 6. Server source and related scripts
COPY --from=builder /app/server.ts           ./
COPY --from=builder /app/next.config.ts      ./
COPY --from=builder /app/tsconfig.json       ./
COPY --from=builder /app/instrumentation.ts  ./
COPY --from=builder /app/lib                 ./lib
COPY --from=builder /app/package.json        ./

# Copy entrypoint script.  We retain the existing docker-entrypoint.sh
# script from the repository which performs database migrations and
# starts the custom server via tsx.
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Create uploads directory (writable by the non-root user)
RUN mkdir -p public/uploads && chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000
ENV PORT=3000 \
    HOSTNAME=0.0.0.0

# Health check — wget is installed above.  Use a generous start period
# to allow for database migrations on first run.
HEALTHCHECK --interval=15s --timeout=10s --start-period=180s --retries=12 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1

ENTRYPOINT ["/docker-entrypoint.sh"]
