export type DeliveryState = 'QUEUED' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED';

export type SocketMessagePayload = {
  id: string;
  senderId: string;
  recipientId?: string | null;
  groupId?: string | null;
  type: number;
  ciphertext: string;
  nonce: string;
  fileUrl?: string | null;
  fileName?: string | null;
  fileSize?: number | null;
  wrappedFileKey?: string | null;
  wrappedFileKeyNonce?: string | null;
  fileNonce?: string | null;
  createdAt: string;
  deliveryStatus: DeliveryState;
  readAt?: string | null;
  tempId?: string | null;
  idempotencyKey?: string | null;
  editedAt?: string | null;
  replyToId?: string | null;
  replyTo?: { id: string; senderId: string; ciphertext: string; nonce: string; createdAt: string; isDeleted?: boolean } | null;
  forwardedFrom?: string | null;
  reactions?: Array<{ emoji: string; userId: string; createdAt: string }> ;
  keyGeneration?: number | null;
  messageIndex?: number | null;
  ttlSeconds?: number | null;
  expiresAt?: string | null;
  audioDuration?: number | null;
  waveformData?: string | null;
  _self?: boolean;
};
