-- Explicit alignment migration replacing runtime schema patching.
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "needsPasswordChange" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lockoutUntil" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpSecret" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "totpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isApproved" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "recoveryQuestion" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "recoveryAnswerHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "identityKeyPublic" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "signedPreKey" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "signedPreKeySig" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "signingPublicKey" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "e2eeVersion" TEXT NOT NULL DEFAULT 'legacy';

ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "isSetupCompleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "isRegistrationEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "maxRegistrations" INTEGER;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "isCaptchaEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "recaptchaSiteKey" TEXT;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "recaptchaSecretKey" TEXT;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "maxAttachmentSize" INTEGER NOT NULL DEFAULT 10485760;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "allowedFileFormats" TEXT NOT NULL DEFAULT '*';
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "reservedUsernames" TEXT NOT NULL DEFAULT 'admin,administrator,support,moderator,root,sys';
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "rules" TEXT;
ALTER TABLE "AdminSettings" ADD COLUMN IF NOT EXISTS "firebaseConfig" TEXT;
