apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elahe-messenger.fullname" . }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  LOG_FORMAT: {{ .Values.env.LOG_FORMAT | quote }}
  LOG_DESTINATIONS: {{ .Values.env.LOG_DESTINATIONS | quote }}
  DATABASE_HOST: {{ ternary .Values.database.host (printf "%s-postgresql" (include "elahe-messenger.fullname" .)) .Values.database.external | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  REDIS_URL: {{ if .Values.redis.enabled }}{{ printf "redis://%s-redis:6379" (include "elahe-messenger.fullname" .) | quote }}{{ else }}""{{ end }}
