apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elahe-messenger.fullname" . }}-secret
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  DATABASE_USER: {{ .Values.database.user | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | quote }}
  BACKUP_ENCRYPTION_KEY: {{ .Values.secrets.backupEncryptionKey | quote }}
